### PR TITLE
Moon image tiles

### PR DESCRIPTION
**Pull request by ilan-gold**
These are the image tiles mentioned in https://github.com/uber/deck.gl/issues/4230#issuecomment-590524220.

### CODE REVIEW

**Comment by ibgreen** [comment]
We always add a README referencing the src of the data files in each directory, also mentioning the license under which they are included.

**Comment by ilan-gold** [comment]
http://lroc.sese.asu.edu/about/terms Terms here, commit incoming.

**Comment by ilan-gold** [comment]
Corresponding PR: https://github.com/uber/deck.gl/pull/4328

**Comment by ibgreen** [comment]
Yes, this looks good. Since I seem to have lost merge privileges on this repo, can you merge for now @Pessimistress ?

@ilan-gold Thanks for working through the issues. As soon as this is merged you should be able to access this data with `rawgithubusercontent` type link, similar to other examples.

**Pull request merged**
